Migrate NodeJs Javascript to Typescript
Valdior/WASB-Back pull request #10
Opened 2024-04-24 13:01 UTC by Valdior

2024-04-25 00:22 UTC, KeotiseuF requested changes

2024-04-25 00:22 UTC, KeotiseuF commented on src/controllers/security.controller.ts
Faudrait déplacer le code de registration dans addUser.
![image](https://github.com/Valdior/WASB-Back/assets/101713837/d746b6ac-3443-4689-a5da-ef02d6e9157c)

Puis supprimer ce fichier pour soit créer un dossier middlewares avec un nouveau fichier ou créer le fichier directement dans le dossier validators, ce fichier contiendrait le script qui checkerai si l'utilisateur à le droit ou pas de faire cette requête (Guard), on la placerai dans la route juste avant la requête de registration. Faudrait voir si l'utilisateur est connecté avec son Wallet ou non. 
![image](https://github.com/Valdior/WASB-Back/assets/101713837/9c2e8711-981d-4a67-aff1-0c4e2a93f9f0)

2024-04-25 00:22 UTC, KeotiseuF commented on src/models/user.model.ts
Cela fait pas mal de propriété pour un modèle je voyais plus une ligne réseaux sociaux qui serait un objet contenant tout les réseaux, car si je me trompe pas par le suite les utilisateurs pourrons ajouter d'autres réseaux

2024-04-25 11:31 UTC, Valdior commented on src/models/user.model.ts
Cela ne reviendrait il pas au même ? 
Si on ajout un réseau dans ton objet, qu'adviendra-t-il de ceux déjà existant ?

2024-04-25 11:35 UTC, Valdior commented on src/controllers/security.controller.ts
Le addUser était présent pour exemple à la base.
J'ai estimé qu'il pouvait rester, imaginant qu'on pourrait toujours ajouter une nouvelle personne via le panel admin plus tard. Je vais le supprimer.
Je préfère garder le "register" séparer question de securité. L'action étant différente du point de vue des validations et process de sécurité des autres actions sur le user.

2024-04-28 07:44 UTC, Valdior commented on src/controllers/security.controller.ts
Step by step :) 

Le ticket concerne uniquement la migration du JS vers Typescript.
Il y a déjà un autre de prévu pour le système de Guard. Je vais de ce pas ajouter ta proposition de nouveau dossier dans ce ticket.
Nous ne sommes pas vraiment sur une architecture MVC, il n'y a pas de Views.
Ta logique est bonne, et s'est d'ailleurs pour cette raison que l'ajout d'un user passe par le même service.
Je n'ai même pas vraiment de réponse sur le pourquoi j'ai séparé les controllers. J'ai toujours fait la distinction entre ces deux points jusqu'à maintenant... 🤕

2024-04-28 07:47 UTC, Valdior commented on src/models/user.model.ts
Je ne trouve pas cela plus simple, mais pas plus compliqué non plus.
d'acc je vais faire ca

2024-04-28 10:53 UTC, KeotiseuF commented on src/controllers/security.controller.ts
My bad 😅 
Je pensais, bon bah je retire ce que j'ai dis alors 😁

2024-04-30 08:51 UTC, KeotiseuF approved these changes

2024-04-30 09:29 UTC, merged